### ISSUE TITLE
Ful text

### ISSUE THREAD

**Issue by deedeeharris** [shauryr/S2QA#10]
Amazing app! Thanks!

Does the live demo query the entire text of the article or only the title and abstract?

Which notebook is good for searching Google Scholar for articles and querying them to get results with references?

Thank you.

**Comment by shauryr** [comment]
hi! Thank you!

The live demo just queries the abstracts. 
I dont have a notebook for google search yet but it will search semantic scholar domain using google search. Have a look here  - https://github.com/shauryr/S2QA/tree/master/serp_api_qa

**Comment by shauryr** [comment]
@deedeeharris Full text access was added to the llama hub data loader. Please have a look at it here - https://github.com/emptycrown/llama-hub/tree/main/llama_hub/semanticscholar#some-preliminaries
